### ISSUE TITLE
Game crashes at startup

### ISSUE THREAD

**Issue by hottycat** [p455w0rd/WirelessCraftingTerminal#31]
Game crashes at startup. With WirelessCraftingTerminal disabled starts without issues. WCT 1.6b rv3 same, no issues at startup. Log here:

http://pastebin.com/TdKfTDBZ

I don't know much about Minecraft modding but importing packages that do not exist throws an exception in Java. Is this handled differently in Minecraft?

**Comment by p455w0rd** [comment]
no..but if you open the jar, the package exists..it's included

**Comment by p455w0rd** [comment]
I'm stumped atm on this one..this classes it's saying aren't there are obviously there..i'll have to think on this one

**Comment by p455w0rd** [comment]
I think I may just remove IC2 support tbh

**Comment by hottycat** [comment]
> no..but if you open the jar, the package exists..it's included

Ah, I see. Makes sense.

> I'm stumped atm on this one..this classes it's saying aren't there are obviously there..i'll have to think on this one

I can try to help you. Just tell me what you need.

**Comment by p455w0rd** [comment]
that's the thing..this makes absolutely zero sense and I'm unable to reproduce the error..everything works fine on my end..in my test (not dev, but actual live) environment I only have ae2, wct, nei, and waila installed...works perfectly

**Comment by p455w0rd** [comment]
the only thing I can think is that another one of those mods is messing with something that's messing with the order that the game registers items..the terror at the top is essentially saying that ItemWirelessCraftingTerminal isn't registered

**Comment by hottycat** [comment]
In that case one of the many mods I use is the issue. I'm gonna try to find the one. If it is one of the bigger mods this issue could affect other users

**Comment by p455w0rd** [comment]
just setup a small instance of mc and only put ae2/wct in and see if it runs

**Comment by hottycat** [comment]
Disabled all mods except AE2 and WCT. Game starts without issues. This is clearly on my end. Sorry to take your time.

**Comment by p455w0rd** [comment]
still..i would like to know if you figure this out..this means my mod is conflicting with another and I'd like to resolve it..I may even know what it is after doing a little looking

**Comment by hottycat** [comment]
Yeah, I'm currently going through it.Just takes a little bit of time.

**Comment by p455w0rd** [comment]
thanks! =D

**Comment by hottycat** [comment]
The somewhat expected culprit, it is NEI (why is it always the mods by chicken_bones?). The unexpected side of it, it isn't NEI alone. It seems like 2 or 3 mods in combination with the new version of WCT causes the issue.

I'm going to find the exact combination of mods tomorrow, I have to go to bed. Tomorrow is a long day for me.

**Comment by hottycat** [comment]
So after some testing Minefactory Reloaded or Mekanism in combination with NEI crashes the game at startup. If NEI or the other two mods are disabled the game starts without a hitch.

While researching if found this issue (https://github.com/aidancbrady/Mekanism/issues/1742) on the mekanism github. Especially this comment (https://github.com/aidancbrady/Mekanism/issues/1742#issuecomment-56076235) is interesting. After downloading the IC2 API from http://wiki.industrial-craft.net/?title=Download#API_2 I can activate all mods and the game starts.

**Comment by p455w0rd** [comment]
ok..this almost confirms what I was thinking..I'm only including the needed parts of the IC2 api, but I think I need to include the entire Item API..i'll get a hotfix version baked for you to test in a few minutes...working on my 1.9 mod atm so it may be 30 mins or so. Thank you so much for doing this research. You will be added to the contributors list for putting in this much time to to help me solve this issue. =D

**Comment by p455w0rd** [comment]
try this version: http://p455w0rd.net/mc/WCT/WirelessCraftingTerminal-1.7.10-rv3-1.7.2b.jar

**Comment by hottycat** [comment]
Did not work :(

 java.lang.NoClassDefFoundError: net/p455w0rd/wirelesscraftingterminal/items/ItemWirelessCraftingTerminal

**Comment by p455w0rd** [comment]
but it does work with the IC2 lib?

**Comment by hottycat** [comment]
Yes, it does.

**Comment by p455w0rd** [comment]
this weird because I included the entire lib in the mod..well..i'll work to reproduce the bug by installing those mods in my dev env and will post back when I have it resolved

**Comment by p455w0rd** [comment]
Also, that issue comment is correct, we technically shouldn't include the APIs in our mods. The reason we do it is so people don't have to download more than one file. Still, it is my opinion that if this only happens with Mekanism and with none of the hundreds of other mods that use the IC2 API (whether embedded or external) the issue is with them. I removed the coremod from this mod as it was buggy and it wasn't doing what it was supposed to as far as disabling IC2 integration when IC2 was installed. It said IC2 integration was disabled, but it actually wasn't. This is what was initially causing this issue's problem. At any rate, rest assured that I will find a solution. Removing IC2 support is definitely in line if something doesn't pan out quick as I don't even like the mod myself (actually, it's more the decisions the devs make than the mod itself)...

**Comment by hottycat** [comment]
As far as I'm concerned I'm fine with adding another library separately to play with your mod. Dependencies are a good thing because it means less code to load and run in Minecraft. However what I don't like is that the IC2 Api is not available on curse  (as far as I know) and the download of it is pretty hidden. 

A solution to this is perhaps catching this exception (if possible in Forge) and ignore the code that is handling the IC2 integration if thrown.

**Comment by p455w0rd** [comment]
well if it's possible in Java, it's possible in Forge. basically in ItemWirelessCraftingTerminal, it implements the necessary IC2 interfaces. I wouldn't know how to do catch/throw in implementations. This is exactly what the coremod was supposed to do. Via ASM it would iterate through a list of custom annotations which listed which implementations were used in the associated class files. and if the mod couldn't be found (in this case IC2) it was supposed to remove the implementations/class inclusions. If you know of a way I can do this without dirty ASM trickery, I'm all ears =D

**Comment by p455w0rd** [comment]
have you tried updating to the latest Mekanism? loads fine for me

**Comment by hottycat** [comment]
You mean 8.1.9.267? Already using it.

**Comment by p455w0rd** [comment]
I dunno exactly..I'm using a version I compiled myself from the latest 1.7.10 source. Get it here and let me know if the crash still happens. If it does, then I don't think It's a Mekanism issue. MekanismAll-1.7.10-8.1.9.homebaked.jar

**Comment by hottycat** [comment]
I don't think this link works.

**Comment by p455w0rd** [comment]
just DL'ed it

**Comment by hottycat** [comment]
I mean it does not show up as a link.

**Comment by p455w0rd** [comment]
so did u ever Dl and try it?

**Comment by adamcirillo** [comment]
Have you got and rv2 build with the fix i'm having the same issues I have mechanism and mfr installed as well

**Comment by p455w0rd** [comment]
I can have..I don't know that it'll fix it though..we're working on finding the root cause right now..I can build an rv2 version, but you must reply with whether it fixes it or now..if not then I'll probably just remove IC2 support and post a hotfix

**Comment by adamcirillo** [comment]
i can do that for you right now if you want

**Comment by p455w0rd** [comment]
http://p455w0rd.net/mc/WCT/WirelessCraftingTerminal-1.7.10-rv2-1.7.2b.jar

**Comment by adamcirillo** [comment]
okay so it still crashes unless i disable mechanism and mfr

**Comment by p455w0rd** [comment]
give me 20mins..this isn't worht the headache..I'm going to remove IC2 support..problem solved =D

**Comment by hottycat** [comment]
After reloading the page the download link appeared. Still, the game crashes.

I'm going to set up a vm tomorrow and try to work a little bit on this one. It's been a while since I worked in Java but perhaps we can find a solution to keep the IC2 integration into this mod.

**Comment by p455w0rd** [comment]
yeah I would like to keep it..but for the sake of keeping users happy..It has been remove for the time being..just running tests now to make sure everything else is functional, then I'll post the hotfix to curse

**Comment by p455w0rd** [comment]
It's live: http://minecraft.curseforge.com/projects/wireless-crafting-terminal please let me know if this resolves your issues =D

**Comment by adamcirillo** [comment]
Works fine for me I loaded up my world I haven't tested the terminal itself don't have ae set up yet

**Comment by p455w0rd** [comment]
cool..thanks for the input =D
